sudo: required
services:
  - docker

script:
  - wget https://raw.githubusercontent.com/blang/latex-docker/master/latexdockercmd.sh
  - chmod +x latexdockercmd.sh
  - ./latexdockercmd.sh latexmk -pdf -outdir=./_build

before_deploy:
  - echo "$HEROKU_API_KEY" | docker login -u _ --password-stdin registry.heroku.com
  - docker build -t iglinsek/web .
  - docker tag iglinsek/web registry.heroku.com/$HEROKU_APP_NAME/web
  - docker push registry.heroku.com/$HEROKU_APP_NAME/web
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh  
deploy:
  provider: script
  script: heroku container:release web --app=$HEROKU_APP_NAME
  skip_cleanup: true
  on:
    branch: master