sudo: required
services:
  - docker

before_install:
  - echo "$HEROKU_PASSWORD" | docker login -u _ --password-stdin registry.heroku.com

script:
  - wget https://raw.githubusercontent.com/blang/latex-docker/master/latexdockercmd.sh
  - chmod +x latexdockercmd.sh
  - ./latexdockercmd.sh latexmk -pdf -outdir=./_build

deploy:
  provider: script
  script:
    - docker build -t iglinsek/web .
    - docker tag iglinsek/web registry.heroku.com/$HEROKU_APP_NAME/web
    - docker push registry.heroku.com/$HEROKU_APP_NAME/web
  on:
    branch: master
