name: CI
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Ignacio_Glinsek-CV.tex
      - name: Check pdf files
        run: |
          set -e
          file Ignacio_Glinsek-CV.pdf | grep -q ' PDF ' 
      - uses: actions/upload-artifact@v2
        with:
          name: cv
          path: Ignacio_Glinsek-CV.pdf
  deploy:
    runs-on: ubuntu-latest
    needs: build_latex
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/download-artifact@v2
        with:
          name: cv
          path: pdf
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: master
          folder: ./pdf
          repository-name:  nakioman/nakioman.github.io
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          CLEAN: false
